### ISSUE TITLE
Syntax highlighting not working after declaring a string

### ISSUE THREAD

**Issue by dfarache** [MattFryer/Qlik-Web-Highlight#17]
Hello,

Congrats on this project. It is a great piece of work.

We have noticed that the syntax highlighting does not work when a string is initialized as you may see in the picture below.

Upon closer inspection, it seems that the highlighter encloses a big piece of code as a hljs-string instead of just the string itself.

![qvs-highlighter-strings-issue](https://user-images.githubusercontent.com/5766203/36094331-0e07f1d4-0fee-11e8-8583-2479cf8db191.PNG)

**Comment by MattFryer** [comment]
Hi David
Is there a backslash at the end of your string by any chance? If so I think it's behaving as an escape character and so the closing single quote isn't being considered the end of the string. 

Regards
Mat

**Comment by dfarache** [comment]
Hi Matt,

Thanks for the quick response. 

You are right, there is a backlash, because the variable stores a path to a directory. I understand now why it is failing. Do you think this can be considered still as an issue with the highlighter?

Regards,
David

**Comment by MattFryer** [comment]
Yes it is definitely an issue as it isn't correct behaviour for Qlik script. I've just checked and it is currently using the default highlight.js string identifiers which allow backslash escaping. Can you try this package instead for me and let me know if it fixes the problem:

[highlight.pack.zip](https://github.com/MattFryer/Qlik-Web-Highlight/files/1716364/highlight.pack.zip)

**Comment by dfarache** [comment]
Perfect!! it works just fine.

Thanks so much for the quick fix!

**Comment by MattFryer** [comment]
No problem. I'll roll it into the next release.

Out of interest, are you using this internally within Qlik?

**Comment by dfarache** [comment]
Yes, I use it personally as a developer working for Qlik. I can't say if others are using it as well, though.
