### ISSUE TITLE
WordPress display QW-code as a gray box

### ISSUE THREAD

**Issue by slivka83** [MattFryer/Qlik-Web-Highlight#18]
Hello.

I install your plugin, but my WordPress display QW-code as a gray box.
Wath you mean when write:
> You can add your own CSS targeting the "qlik-highlight" class as follows:
> pre.qlik-highlight-pre { } 
> To apply styling to the <code> tag, use:
> code.qlik-highlight-code { }

What I should do?

**Comment by MattFryer** [comment]
Hi
Sounds like the styling of the code block isn’t quite right. Can you share a link to the sight where you’re seeing the problem?

Regards
Matt

**Comment by slivka83** [comment]
I created test post: http://beeclick.ru/?p=111

**Comment by MattFryer** [comment]
Hi
It looks to be working quite normally. The default styling for many WordPress themes is to display <pre><code> tags in this way with a grey box. You can add some simple CSS to remove it if you wish. In the WordPress admin, go to Appearance -> Edit CSS. Then add the following:

pre.qlik-highlight-pre {
    background: none;
    border: none;
    padding: unset;
}

Regards
Matt

**Comment by slivka83** [comment]
Thank you. The grey box was gone, but the code is not highlight.

**Comment by MattFryer** [comment]
I just checked and the code is highlighting perfectly for me. Your browser must be blocking the JS.

![2018-05-26](https://user-images.githubusercontent.com/8959047/40580738-2d1e9e9c-613d-11e8-9c92-02c5ebb81750.png)

**Comment by slivka83** [comment]
I checked in different browsers:
Firefox, IE, Edge:
![2018-05-27_223605](https://user-images.githubusercontent.com/8715000/40589921-b9a526f8-61fe-11e8-964b-dc9d0dba192e.png)
Chrome:
![2018-05-27_223911](https://user-images.githubusercontent.com/8715000/40589925-cd39c246-61fe-11e8-801c-48db9e1caecb.png)

**Comment by slivka83** [comment]
Manually downloaded and config qvhighlight_vX.X.zip. Now code highlight correct.

**Comment by MattFryer** [comment]
Hi, glad you got it sorted.

Regards
Matt
